/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhops;

import java.awt.Color;
import static java.awt.Color.red;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author cassi
 */
public class JanelaPrincipal extends javax.swing.JFrame {
   //Variaveis
    private Memoria memoria; //Memoria
    private DefaultListModel<String> model;
    private final int PC,SP,ACC,OPM,IR,IM; //Variaveis para guardar a referencia aos registradores
    private Registrador[] regs; //Vetor de registradores
    private int leitura; //Leitura do usuario
    private Boolean run,opcaoRun; //Variaveis auxiliares de continuidade
    private String nomeUsuario;
    private final String ARQUIVO_ENTRADA = "src/inputs/arquivo.txt";
    
    private void imprimeRegistradoresNaTela() { //Funçao que atualiza os valores dos registradores para imprimir no display
        //Imprime os valores dos registradores na tela   
        regs[IR].setRegistrador(memoria.getMemoria().get(memoria.getINICIO_INS_DADOS()));
        acc.setText(FuncoesUteis.registradorDisplay(regs[ACC]));
        im.setText(FuncoesUteis.registradorDisplay(regs[IM]));
        ir.setText(regs[IR].getRegistrador());
        opm.setText(regs[OPM].getRegistrador());
        sp.setText(FuncoesUteis.registradorDisplay(regs[SP]));
        pc.setText(FuncoesUteis.registradorDisplay(regs[PC]));
    }
    /**
     * Creates new form janelaprincipal
     */
    public JanelaPrincipal(String nome) throws FileNotFoundException {
        initComponents();
        nomeUsuario = nome;
        //run = true;
        opcaoRun = false;
        campo1.setOpaque(false);
        campo1.setBackground(new java.awt.Color(255, 255, 255, 0));
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255, 0));
        jButton1.setOpaque(false);
        jButton1.setBackground(new java.awt.Color(255, 255, 255, 0));
        jList1.setOpaque(false);
        jList1.setCellRenderer(new TransparentListCellRenderer());
        jScrollPane3.setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);
        jButton2.setOpaque(false);
        jButton2.setBackground(new java.awt.Color(255, 255, 255, 0));
        jButton3.setOpaque(false);
        jButton3.setBackground(new java.awt.Color(255, 255, 255, 0));
        jTextArea1.setText("	Olá, "+nomeUsuario+"!\n Bem vindo ao Venture! \n Escolha o seu modo de operação para começarmos...\n\n Step - Executa o programa passo a passo\n Run - Executa todo o programa\n Reset - Reset o programa");
        ManipulaArquivo arquivo;
        regs = new Registrador[6];//declaracao dos registradores que serao usados no programa. Nao tem diferenciacao sobre qual registrador eh qual.
        model = new DefaultListModel<String>();
        memoria = new Memoria(regs);
        //referencias os registradores no vetor regs 
        IM = 5; 
        IR = 4;  
        OPM = 3; 
        ACC = 2; 
        SP = 1; 
        PC = 0;  
        // ex: valorRegistradorAcc = regs[ACC].getRegistrador()
        
        arquivo = new ManipulaArquivo(ARQUIVO_ENTRADA, memoria);//pacote com as possiveis entradas
        
       /* do {
            run = arquivo.leitor();//faz a leitura do arquivo, guardando o valor de retorno da funçao. Quando for false (0), sai do loop
        } while (run);*/

        while(arquivo.leitor());//sintaxe alternativa

        //memoria.imprimeMemoria();//Debug
        
        for (int i = 0; i<memoria.getMemoria().size();i++){
            model.addElement(memoria.getMemoria().get(i));
        }
        
        //Seta o vetor memória da interface 
        jList1.setModel(model);
        
        
        this.imprimeRegistradoresNaTela();
             
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pc = new javax.swing.JLabel();
        sp = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();
        campo1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        opm = new javax.swing.JLabel();
        ir = new javax.swing.JLabel();
        im = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        pc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pc.setText("0");
        jPanel1.add(pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 192, 32));

        sp.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        sp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sp.setText("0");
        jPanel1.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 192, 32));

        acc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        acc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc.setText("ADD");
        jPanel1.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 192, 32));

        campo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campo1.setBorder(null);
        campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo1ActionPerformed(evt);
            }
        });
        jPanel1.add(campo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 560, 208, 30));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Step");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 90, 30));

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 400, 90, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 464, 288, 112));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\t      Olá! Bem vindo ao Venture! \nEscolha o seu modo de operação para começarmos...\n\nStep - Executa o programa passo a passo\nRun - Executa todo o programa\nReset - Reset o programa");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 280, 120));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jScrollPane3.setViewportView(jList1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 540));

        opm.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        opm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opm.setText("0");
        jPanel1.add(opm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 208, 32));

        ir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ir.setText("0");
        jPanel1.add(ir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 192, 32));

        im.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        im.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        im.setText("0");
        jPanel1.add(im, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 192, 32));

        jButton3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton3.setText("Run");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 400, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalhops/background ps.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //A função abaixo espera um entrada do input, ela é executada com a tecla enter
    private void campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo1ActionPerformed
        
        int posicao; //posiço de memoria
        int operacao; //opcode
        int aux; // aux = valor auxiliar para operações aritméticas
        String opcode;
        
        posicao = regs[PC].getRegistradorInt(); // pega a posição da instrução de PC
        opcode = memoria.getMemoriaPosicao(posicao);        // pega a instrução da memória
        //regs[IR].setRegistrador(opcode);                    // guarda no registrador de instrução
        operacao = FuncoesUteis.binaryStringToInt(opcode);  // converte para int para ficar fácil de operar
        
        // realiza a operação
        if(operacao == 12 || operacao == 44){
            leitura = Integer.parseInt(campo1.getText());
            System.out.println(leitura);
            jTextArea1.setText(campo1.getText());

            executarOperacao();
            if(opcaoRun){
                runButton();
            }
            
            this.imprimeRegistradoresNaTela();

            DefaultListModel<String> model = new DefaultListModel<String>();
            for (int i = 0; i<memoria.getMemoria().size();i++){
                model.addElement(memoria.getMemoria().get(i));
            } 
        }
        
        
        //jLabel5.setText(campo1.getText());
    }//GEN-LAST:event_campo1ActionPerformed
    //essa função executa o botão step quando ele é clicado
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       int posicao, operacao; // aux = valor auxiliar para operações aritméticas
        String opcode;
        
        posicao = regs[PC].getRegistradorInt(); // pega a posição da instrução de PC
        opcode = memoria.getMemoriaPosicao(posicao);        // pega a instrução da memória
        //regs[IR].setRegistrador(opcode);                    // guarda no registrador de instrução
        operacao = FuncoesUteis.binaryStringToInt(opcode);  // converte para int para ficar fácil de operar
        
        // realiza a operação
        if(operacao == 12 || operacao == 44){
            jTextArea1.setText("Esperando leitura.\nDigite um valor decimal válido\npara não dar pau no programa.\nClique enter para confirmar.");
        }else{
            executarOperacao();
        }

        this.imprimeRegistradoresNaTela();
       
        DefaultListModel<String> model = new DefaultListModel<String>();
        for (int i = 0; i<memoria.getMemoria().size();i++){
            model.addElement(memoria.getMemoria().get(i));
        }
        jList1.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            resetButton();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void resetButton() throws FileNotFoundException{
        opcaoRun = false;
        jLabel5.setText(""); 
        campo1.setText("");
        model = new DefaultListModel<String>();
        memoria = new Memoria(new Registrador[6]);
        jTextArea1.setText("	Olá, "+nomeUsuario+"! Bem vindo ao Venture! \n Escolha o seu modo de operação para começarmos...\n\n Step - Executa o programa passo a passo\n Run - Executa todo o programa\n Reset - Reset o programa");
        ManipulaArquivo arquivo = new ManipulaArquivo(ARQUIVO_ENTRADA, memoria);//pacote com as possiveis entradas
        
        while(arquivo.leitor());

        memoria.imprimeMemoria();
        for (int i = 0; i<memoria.getMemoria().size();i++){
            model.addElement(memoria.getMemoria().get(i));
        }
        this.imprimeRegistradoresNaTela();
        
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Fechando jf = new Fechando();
        jf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed
    public void runButton(){
        run = true;
        while(run){
            
//            try {
//                Thread.sleep(2000);
                //System.out.println("loop");
                int posicao, operacao; // aux = valor auxiliar para operações aritméticas
                String opcode;

                posicao = regs[PC].getRegistradorInt(); // pega a posição da instrução de PC
                opcode = memoria.getMemoriaPosicao(posicao);        // pega a instrução da memória
                //regs[IR].setRegistrador(opcode);                    // guarda no registrador de instrução
                operacao = FuncoesUteis.binaryStringToInt(opcode);  // converte para int para ficar fácil de operar

                // realiza a operação
                if(operacao == 12 || operacao == 44){
                    //executarOperacao();
                    jTextArea1.setText("Esperando leitura.\nDigite um valor decimal válido\npara não dar pau no programa.\nClique enter para confirmar.");
                    run = false;
                }else{
                    executarOperacao();
                }
//            } catch (InterruptedException ex) {
//                Logger.getLogger(janelaprincipal.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        opcaoRun = true;
        runButton(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    public JList<String> getLista() {
        return jList1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
     

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JTextField campo1;
    private javax.swing.JLabel im;
    private javax.swing.JLabel ir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel opm;
    private javax.swing.JLabel pc;
    private javax.swing.JLabel sp;
    // End of variables declaration//GEN-END:variables

    public void executarOperacao() {
        int posicao, operacao, aux; // aux = valor auxiliar para operações aritméticas
        String opcode, operando1, operando2;
        
        posicao = regs[PC].getRegistradorInt(); // pega a posição da instrução de PC
        opcode = memoria.getMemoriaPosicao(posicao);        // pega a instrução da memória
        regs[IR].setRegistrador(opcode);                    // guarda no registrador de instrução
        operacao = FuncoesUteis.binaryStringToInt(opcode);  // converte para int para ficar fácil de operar
        
        // realiza a operação

        // pega operando (é repetido em casa case)
        regs[IR].setRegistrador(opcode);
        ir.setText(regs[IR].getRegistrador());

        switch (operacao) {//Seleciona a operação e verifica o
            // ADD
            case 2:   // add direto
            case 34:  // add indireto
            case 130: // add imediato
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                )
                                ); 
                    jTextArea1.setText("As informações foram adicionadas\nindiretamente no Acumulador.\n\n(ACC <- ACC+OP1)");
                    
                } else if (opcode.charAt(8) == '1') { // operando imediato
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("As informações foram adicionadas\nimediatamente no Acumulador.\n\n(ACC <- ACC+OP1)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("As informações foram adicionadas\ndiretamente no Acumulador.\n\n(ACC <- ACC+OP1)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                System.err.println(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                // executa operação
                regs[ACC].add(operando1);
                regs[PC].add(2);
                break;
                
            // BR
            case 0:  // br direto
            case 32: // br indireto
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Salto informacional indireto realizado.\n\n(PC <- opd1)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Salto informacional direto realizado.\n\n(PC <- opd1)");
                }
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
              
                // executa operação
                regs[PC].setRegistrador(operando1);
                break;
                
            // BRNEG
            case 5:  // brneg direto
            case 37: // brneg indireto
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Testando negatividade do ACC\npara salto informacional indireto...\n\n(PC <- opd1, se ACC < 0)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Testando negatividade do ACC\npara salto informacional indireto...\n\n(PC <- opd1, se ACC < 0)");
                }
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                if (regs[ACC].getRegistradorInt() < 0){
                    regs[PC].setRegistrador(operando1);
                    jTextArea1.setText("Salto informacional permitido.\n\n(PC <- opd1, se ACC < 0)");
                }else{
                    regs[PC].add(2);
                    jTextArea1.setText("Salto informacional negado.\n\n(PC <- opd1, se ACC < 0)");
                }
                break;
            
            // BRPOS
            case 1:  // brpos direto
            case 33: // brpos indireto
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Testando positividade do ACC\npara salto informacional indireto...\n\n(PC <- opd1, se ACC > 0)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Testando positividade do ACC\npara salto informacional direto...\n\n(PC <- opd1, se ACC > 0)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
        
                // executa operação
                if (regs[ACC].getRegistradorInt() > 0){
                    regs[PC].setRegistrador(operando1);
                    jTextArea1.setText("Salto informacional permitido.\n\n(PC <- opd1, se ACC > 0)");
                }else{
                    regs[PC].add(2);
                    jTextArea1.setText("Salto informacional negado.\n\n(PC <- opd1, se ACC > 0)");
                }
                break;
                
            // BRZERO
            case 4:  // brzero direto
            case 36: // brzero indireto
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Testando nulidade do ACC\npara salto informacional indireto...\n\n(PC <- opd1, se ACC = 0)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Testando nulidade do ACC\npara salto informacional direto...\n\n(PC <- opd1, se ACC = 0)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                if (regs[ACC].getRegistradorInt() == 0){
                    regs[PC].setRegistrador(operando1);
                    jTextArea1.setText("Salto informacional permitido.\n\n(PC <- opd1, se ACC = 0)");
                    
                }else{
                    regs[PC].add(2);
                    jTextArea1.setText("Salto informacional negado.\n\n(PC <- opd1, se ACC = 0)");
                }            
                break;
            
            // CALL
            case 15: // call direto
            case 47: // call indireto
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Salvando progresso e\niniciando Sub-programa indireto.\n\n([SP] <- PC; PC <- opd1)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Salvando progresso e\niniciando Sub-programa direto.\n\n([SP] <- PC; PC <- opd1)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                if (regs[SP].getRegistradorInt() + 1 < memoria.getINICIO_INS_DADOS()) { // verifica se está dentro dos limites da pilha
                    regs[PC].add(2);
                                   //(int local, String valor)
                    memoria.setMemoriaPosicao(regs[SP].getRegistradorInt(), regs[PC].getRegistrador());
                    regs[PC].setRegistrador(operando1);
                    regs[SP].add(1);
                } else {
                    // stack overflow
                    jTextArea1.setText("Ocoreu um stack overflow na pilha.\n");
                }
                break;
                
            // COPY
            case 13:  // copy direto-direto
            case 45:  // copy indireto-direto
            case 77:  // copy direto-indireto
            case 109: // copy indireto-indireto
            case 141: // copy direto-imediato
            case 173: // copy indireto-imediato
                if (opcode.charAt(10) == '1') { // operando 1 indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Computador central indiretamente selecionado");
                } else { // operando 1 direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Computador central diretamente selecionado");
                }
                if (opcode.charAt(9) == '1') { // operando 2 indireto
                    operando2 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+2)
                                )
                                ); 
                    jTextArea1.setText("Dados selecionados indiretamente\nda Estação Subespacial");
                } else if (opcode.charAt(8) == '1') { // operando 2 imediato
                    operando2 = memoria.getMemoriaPosicao(posicao+2);
                    jTextArea1.setText("Dados selecionados imediatamente\nda Estação Subespacial");
                } else { // operando 2 direto
                    operando2 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+2)
                                );
                    jTextArea1.setText("Dados selecionados diretamente\nda Estação Subespacial");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                memoria.setMemoriaPosicao(FuncoesUteis.binaryStringToInt(operando1), operando2);
                regs[PC].add(3);
                jTextArea1.setText("Dados da Estação Subespacial copiados\npara Computador Central com sucesso.\n\n(opd1 <- opd2)");
                break;
                
            // DIVIDE
            case 10:  // divide direto
            case 42:  // divide indireto
            case 138: // divide imediato
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                )
                                ); 
                    jTextArea1.setText("Informações divididas\nindiretamente no Acumulador.\n\n(ACC <- ACC / opd1)");
                } else if (opcode.charAt(8) == '1') { // operando imediato
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Informações divididas\nimediatamente no Acumulador.\n\n(ACC <- ACC / opd1)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Informações divididas\ndiretamente no Acumulador.\n\n(ACC <- ACC / opd1)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                aux = FuncoesUteis.binaryStringToInt(operando1);
                if (aux != 0) { // não pode fazer divisão por 0
                    regs[ACC].setRegistrador(FuncoesUteis.intToBinaryString((int) regs[ACC].getRegistradorInt() / aux, 16));
                } // else erro divisão por 0?
                    //dá pra retornar um erro, ou dá pra deixar o registrador como está
                regs[PC].add(2);
                break;
                
            // LOAD
            case 3:   // load direto
            case 35:  // load indireto
            case 131: // load imediato
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                )
                                );
                    jTextArea1.setText("Informações carregadas de modo\nindireto no Acumulador.\n\n(ACC <- opd1)");
                } else if (opcode.charAt(8) == '1') { // operando imediato
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Informações carregadas de modo\nimediato no Acumulador.\n\n(ACC <- opd1)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Informações carregadas de modo\ndireto no Acumulador.\n\n(ACC <- opd1)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                regs[ACC].setRegistrador(operando1);
                regs[PC].add(2);
                break;
                
            // MULT
            case 14:  // mult direto
            case 46:  // mult indireto
            case 142: // mult imediato
                // pega operando
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                )
                                ); 
                    jTextArea1.setText("Múltiplas informações adicionadas\nindiretamente no Acumulador.\n\n(ACC <- ACC * opd1)");
                } else if (opcode.charAt(8) == '1') { // operando imediato
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Múltiplas informações adicionadas\nimediatamente no Acumulador.\n\n(ACC <- ACC * opd1)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Múltiplas informações adicionadas\ndiretamente no Acumulador.\n\n(ACC <- ACC * opd1)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                aux = FuncoesUteis.binaryStringToInt(operando1);
                regs[ACC].setRegistrador(FuncoesUteis.intToBinaryString(regs[ACC].getRegistradorInt() * aux, 16));
                regs[PC].add(2);
                break;
                
            // READ (TODO)
            case 12: // read direto
            case 44: // read indireto

                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    //jTextArea1.setText("Insira sua identificação de frota estelar para autorizar indiretamente a operação\n ");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    //jTextArea1.setText("Insira sua identificação de frota estelar para autorizar diretamente a operação\n ");
                }
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                //leitura = textFieldAlgumaCoisa.getText();
                //            
                              
                memoria.setMemoriaPosicao(FuncoesUteis.binaryStringToInt(operando1), FuncoesUteis.intToBinaryString(leitura, 16));

                regs[PC].add(2);
                break;
                
            // RET
            case 9: // ret
                if (regs[SP].getRegistradorInt() >= 2) { // verifica se está dentro dos limites da pilha
                    regs[SP].add(-1);
                    regs[PC].setRegistrador(memoria.getMemoriaPosicao(regs[SP].getRegistradorInt()));
                    
                    jTextArea1.setText("Sub-programa finalizado...\nRetomando anterior.\n\n(PC <- [SP])\n(retorno de sub-rotina)");
                } else {
                    jTextArea1.setText("Numero muito pequeno para \n ser representado.");
                }
                
                //Verificar IM aqui
                break;
                
            // STOP (TODO)
            case 11: // stop
                //serve para terminar o laço do botão run
                jTextArea1.setText("Operação Finalizada.");
                run = false;
                
               break;
                
            // STORE
            case 7:  // store direto
            case 39: // store indireto
                // pega operando
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("As Operações realizadas\nforam salvas indiretamente.\n\n(opd1 <- ACC)");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("As Operações realizadas\nforam salvas diretamente.\n\n(opd1 <- ACC)");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                memoria.setMemoriaPosicao(FuncoesUteis.binaryStringToInt(operando1), regs[ACC].getRegistrador());
                regs[PC].add(2);
                break;
                
            // SUB
            case 6:   // sub direto
            case 38:  // sub indireto
            case 134: // sub imediato
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                )
                                ); 
                    jTextArea1.setText("Informações retiradas de modo\nindireto no Acumulador.\n\n(ACC <- ACC - opd1 )");
                } else if (opcode.charAt(8) == '1') { // operando imediato
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Informações retiradas de modo\nimediato no Acumulador.\n\n(ACC <- ACC - opd1 )");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Informações retiradas de modo\ndireto no Acumulador.\n\n(ACC <- ACC - opd1 )");
                }
                
//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                aux = FuncoesUteis.binaryStringToInt(operando1);
                regs[ACC].add(-aux);
                regs[PC].add(2);
                break;
                
            // WRITE
            case 8:   // write direto
            case 40:  // write indireto
            case 136: // write imediato
                if (opcode.charAt(10) == '1') { // operando indireto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                )
                                );
                    jTextArea1.setText("Exibindo indiretamente o dado solicitado");
                } else if (opcode.charAt(8) == '1') { // operando imediato
                    operando1 = memoria.getMemoriaPosicao(posicao+1);
                    jTextArea1.setText("Exibindo imediatamente o dado solicitado");
                } else { // operando direto
                    operando1 = memoria.getMemoriaPosicao(
                                memoria.getMemoriaPosicaoInt(posicao+1)
                                );
                    jTextArea1.setText("Exibindo diretamente o dado solicitado");
                }

//                regs[IM].setRegistrador(Integer.toString(posicao+1));
//                im.setText(regs[IM].getRegistrador());
                
                // executa operação
                // memoria.setMemoriaPosicao(regs[IM].getRegistradorInt,regs[ACC].getRegistrador());//precisa encontrar uma posição
                // tela <- operando1
                jLabel5.setText(Integer.toString(FuncoesUteis.binaryStringToInt(operando1)));
                regs[PC].add(2);
                break;
            
            default: // operação inválida
                jTextArea1.setText("Acesso negado!\nTripulante não reconhecido");
                break;
        }
    }
    
   
}
